version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - db
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0  # Disable OPCache to ease development
      - PHP_EXTENSIONS=pdo,pdo_mysql

    # Command to install extensions when container starts
    command: >
      bash -c "apt-get update && apt-get install -y \
      libzip-dev \
      && docker-php-ext-install pdo pdo_mysql \
      && docker-php-ext-enable pdo pdo_mysql \
      && php-fpm"

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
